

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:testdb
      username: sa
      password:

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/library_schema
#    username: root
#    password: 12341234



  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

---
jwt:
  header: Authorization
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  #token-validity-in-seconds: 86400
  refresh: da21rklmlk2wVMSDKVLSBsd214124LKASFFnfsajfnk512rlpf2klfkasfoapokfjoifhbggSJKDfojoi1u248975102ijflkwnjasfsaklnfalknkgwqrwsjfcnalskfobiSIJODBNLMSDBNVMSLKVDkKFFLAM
  access-token-seconds: 31536000
  refresh-token-seconds: 31536000
